[package]
name = "advanced"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
type_cast_macro = {path = "./type_cast_macro"}
type_cast_macro_derive = {path = "./type_cast_macro/type_cast_macro_derive"}

